# -*- coding: utf-8 -*-
"""Top_500_Cities.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IXd4hJSspZ3Ut79augFQ6UMQij21D74a
"""

!pip install requests --quiet
!pip install beautifulsoup4 --upgrade --quiet
!pip instal lxml

import requests
from bs4 import BeautifulSoup
import pandas as pd

url='https://www.innovation-cities.com/innovation-cities-index-2021-global-500/25718/'

r = requests.get(url, headers={"User-Agent": "XY"})

r

content = r.text

soup=BeautifulSoup(content,'lxml')

table1=soup.find_all('table',id='tablepress-INDEX2021GL')

rank=[]
city=[]
geo=[]
state=[]
reg=[]
bloc=[]
cityid=[]
ccc=[]
cs=[]
cs19=[]
pcr=[]

for t in soup.find_all('tbody'):
  rows=t.find_all('tr')
  for row in rows:
    pl_rank=row.find('td',{'class':'column-1'}).text
    pl_city=row.find('td',{'class':'column-2'}).text
    pl_geo=row.find('td',{'class':'column-3'}).text
    pl_state=row.find('td',{'class':'column-4'}).text
    pl_reg=row.find('td',{'class':'column-5'}).text
    pl_bloc=row.find('td',{'class':'column-6'}).text
    pl_id=row.find('td',{'class':'column-7'}).text
    pl_ccc=row.find('td',{'class':'column-8'}).text
    pl_cs=row.find('td',{'class':'column-9'}).text
    pl_cs19=row.find('td',{'class':'column-10'}).text
    pl_pcr=row.find('td',{'class':'column-11'}).text
    rank.append(pl_rank)
    city.append(pl_city)
    geo.append(pl_geo)
    state.append(pl_state)
    reg.append(pl_reg)
    bloc.append(pl_bloc)
    cityid.append(pl_id)
    ccc.append(pl_ccc)
    cs.append(pl_cs)
    cs19.append(pl_cs19)
    pcr.append(pl_pcr)

dict={'Global Ranking':rank,
      'City':city,
      'GEOGRAPHY':geo,
      'STATE/PROVINCE':state,
      'REGION':reg,
      'BLOC':bloc,
      'CityID':cityid,
      'Current City Classification':ccc,
      'Current Score':cs,
      'Change Since 2019':cs19,
      'Post-COVID 5 year Result':pcr


    
}

df=pd.DataFrame(dict)

df

df.to_csv('Top_500_cities',index=None)

df

